### ISSUE TITLE
Export macros defined with custom-print

### ISSUE THREAD

**Issue by thomashart17** [zheland/custom-print#1]
I have a project that contains several crates and I would like to define macros using custom-print in one crate and be able to export them into the other crates. There doesn't seem to be any feature implemented that allows me to do this. Could this feature be added to the project?

**Comment by zheland** [comment]
Yes, I will try to add this feature during next week.

**Comment by zheland** [comment]
@thomashart17, done :tada: 

Macros now support custom attributes.

Please update `custom-print` dependency version to `1.0.0`.

Example:
```rust
// foo crate:

pub fn write_fn(value: &str) { /* ... */ }

custom_print::define_macros!(#[macro_export] { print, println }, fmt, $crate::write_fn);

// bar crate:

fn main() {
    foo::print!("print");
    foo::println!("println");
}
```

You can check out the full example in `tests/re-export` and `tests/use-re-exported`.

**Comment by thomashart17** [comment]
Great, thank you.
